name: pytest

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama principal si es diferente
  pull_request:
    branches:
      - main  # Cambia 'main' por la rama principal si es diferente

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest
